---
title: "Group 39 CA pollution burden"
author: "Mikel Irigoyen and Teague Tran"
date: "11/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(here)
```

```{r}
ces <- read_csv(here("data", "ces3demographics.csv"))%>% #read in data
  clean_names() #clean names (lowersnakecase)
```
```{r}
ggplot(data = ces, aes(x = white_percent, y = ces_3_0_score)) +
  geom_hex() +
  labs(x = "Percent white", y = "CalEnviroScreen score",
       title = "Pollution Burden Effects on Communities of Color") + 
  scale_fill_gradient(low = "navy", high = "orange") +
  theme_minimal()
```
The overall trend of CalEnviroScreen 3.0 scores show that areas with a lower white population (percent white) have higher scores than ones with higher percentages. This means that communities with a lower proportion of white people tend to experience more pollution burden than ones with more white people, according to CalEnviroScreen. 

